name: Java Checkstyle

on:
  push:
    branches:
      - main
      - "0.[0-9]+.[0-9]+"
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: java-checkstyle-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  java-checkstyle:
    name: Java Checkstyle
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run checkstyle
        run: mvn spotless:apply

      - name: Save checkstyle outcome
        id: git
        continue-on-error: true
        run: |
          git diff-files --quiet

      - name: Create a comment in the PR with the instructions
        if: steps.git.outcome != 'success'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **The Java checkstyle failed.**

            Please run `mvn spotless:apply` in the root of your repository and commit the changes to this PR.
            You can also use [pre-commit](https://pre-commit.com/) to automate the Java code formatting.

            You can install the pre-commit hooks with `make install_test precommit_install`.

      - name: Java checkstyle failed, check the comment in the PR
        if: steps.git.outcome != 'success'
        run: exit 1
